### ISSUE TITLE
Graceful runtime errors

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxtream#30]
**cxtream** should provide graceful runtime errors. For example, data frame should assert and **report** key errors in `cols` method etc.

**Comment by FloopCZ** [comment]
- [ ] Dataframe should check whether cols exist.
- [ ] read_csv should check whether file exists.

**Comment by petrbel** [comment]
@blazekadam @FloopCZ could we implement is asap? it's almost impossible to debug these errors
