### ISSUE TITLE
CSV reader fails when reading a column including spaces

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxtream#36]
`cxtream::read_csv` segfaults when reading a file with spaces (both with and without `"`)

**Comment by FloopCZ** [comment]
Hi, that is strange, do you have an example? Because this is tested:
https://github.com/Cognexa/cxtream/blob/dev/test/core/csv.cpp#L63
And I have loaded large datasets with it without problems.

**Comment by petrbel** [comment]
@FloopCZ it seems like you were right again. The problem is indeed somewhere else.

What is alarming is the manifastion of this error. All I got was this and the print (both `cout` and `cer` after the read didn't happen).
```
*** Error in `/usr/bin/python': double free or corruption (!prev): 0x000055f98d4795f0 ***
[1]    30535 abort (core dumped)
```
I still have no idea how to debug these errors :-(

**Comment by FloopCZ** [comment]
Yeah, it is kind of ugly and it happens who knows where, probably even outside of `cxtream`... I really have no idea what caused the error, but I don't believe it was anything with `csv` reading.

Have you compiled `cxtream` and the dataset in Debug mode? If so, it is possible to run `coredump list`, identify the PID that dumped core and then `coredumpctl gdb PID` and then `bt` to see the backtrace. Than you can carefully browse the frames and identify the source. I can do it when we meet if you don't want to do it yourself.

**Comment by petrbel** [comment]
I tried that yesterday and it led to some boost function... we'll dig into it later on :)
