### ISSUE TITLE
Buffer threads are not ended gracefully

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/cxtream#37]
When working with OpenCV **cxtream** streams and exiting the program, the following OpenCV assertion error is raised:
```
OpenCV Error: Assertion failed (key_ != -1 && "Can't fetch data from terminated TLS container.")
```

This happens only with buffer>1.

**Comment by petrbel** [comment]
I confirm, this has happened to me few times.

**Comment by FloopCZ** [comment]
Yes, you are right, as sloppy as it is, there is no attempt to join the threads in the thread pool destructor.
